# Generated by Django 4.1.7 on 2023-03-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eTodo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'TodoApp_E_Record',
            },
        ),
    ]
