# Generated by Django 4.1.7 on 2023-03-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinguistApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateHistory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.IntegerField()),
                ('rate', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'LinguistApp_db_Rate',
            },
        ),
    ]
