# Generated by Django 4.1.7 on 2023-03-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LinguistApp', '0002_ratehistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ratehistory',
            table='LinguistApp_db_RateHistory',
        ),
    ]
