# Generated by Django 4.1.7 on 2023-02-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eMath',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'MathApp_E_Math',
            },
        ),
    ]
